//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GAG_101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalExperts1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalExperts1()
        {
            this.UserReviews1 = new HashSet<UserReviews1>();
            this.JobTypes1 = new HashSet<JobTypes1>();
        }
    
        public int LocalExpert_ID { get; set; }
        public string LocalExpert_UserID { get; set; }
        public string Name { get; set; }
       
        [EmailAddress]
        public string Email { get; set; }
       
        [Display(Name = "Business Name")]
        public string Business_Name { get; set; }
       
        [Display(Name = "Expertise")]
        public string Name_JobType { get; set; }

        [Display(Name = "Federal Tax Id #")]
        public string BU_FEIN { get; set; }
        [Display(Name = "Zip Code")]
        public Nullable<int> Location_Zip { get; set; }
        [Display(Name = "Phone Number")]
        public string Phone_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [Display(Name = "Ratings")]
        public virtual ICollection<UserReviews1> UserReviews1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]


        [Display(Name = "Type of Expert")]
        public virtual ICollection<JobTypes1> JobTypes1 { get; set; }
    }
}
