//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAG_101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReviews1
    {
        public int Review_ReferenceID { get; set; }
        public int LocalBusiness_ID { get; set; }
        public int LocalExpert_UserID { get; set; }
        public int FairPrice_Rating { get; set; }
        public int Quality_Rating { get; set; }
        public int CompletionTime_Rating { get; set; }
        public string Review_Body { get; set; }
        public System.DateTime ReviewBody_Date { get; set; }
    
        public virtual LocalBusinessUsers1 LocalBusinessUsers1 { get; set; }
        public virtual LocalExperts1 LocalExperts1 { get; set; }
    }
}
